### ISSUE TITLE
Two different images should appear, but only one does

### ISSUE THREAD

**Issue by brooke-guajardo** [krazyito65/discord_pokemon_fusion#11]
/fuse mon1:ekans mon2:onix
Reproducible with the above command. Output currently looks like:
![image](https://user-images.githubusercontent.com/102095955/222834161-eb0f2359-c1f8-49b0-815a-470f3e964638.png)

Should look like:
![image](https://user-images.githubusercontent.com/102095955/222834347-5226c4e7-93c7-4376-b7a9-c9ddb44d0a00.png)

**Comment by krazyito65** [comment]
cant reproduce
